### ISSUE TITLE
Need access rights for pull request

### ISSUE THREAD

**Issue by sriedmueller** [phytec/python-phycam-margin-analysis#4]
Hi @feldmann-phytec, @smk-embedded,
I would need access rights to be able to push my WIP branch to submit my suggested changes.

Thanks,
Stefan

**Comment by feldmann-phytec** [comment]
> Hi @feldmann-phytec, @smk-embedded, I would need access rights to be able to push my WIP branch to submit my suggested changes.
> 
> Thanks, Stefan

Hi @sriedmueller,
where can I change the access rights for you?

**Comment by sriedmueller** [comment]
Hi @feldmann-phytec,
under the settings tab of the project you can find the point collaborators and teams, where you can add me with Write role. That should do it.

**Comment by sriedmueller** [comment]
@smk-embedded, it seems @feldmann-phytec does not have permission to change the access rights, can you please add me?
